Repository RootstockCollective/dao-frontend, pull requests merged in 2025-08, with the labels that each got.

#1255 DAO-1427: Add voting power validation to “Create Proposal” button in proposal hero image
  src/app/proposals/new/components/VotingPowerWrapper.tsx
  src/app/proposals/new/layout.tsx
  src/app/proposals/page.tsx
  src/components/LoadingSpinner/VotingPowerLoading.stories.tsx
  src/components/LoadingSpinner/VotingPowerLoading.tsx
  src/components/LoadingSpinner/index.ts
  src/shared/walletConnection/types.ts
Labels: dao

#1259 TOK-872: add missing file
  cypress/screenshots/health-spec.cy.ts/Health spec -- Visits health (failed).png
  cypress/screenshots/health-spec.cy.ts/Health spec -- Visits health and makes sure Page is OK exists (failed).png
  src/app/proposals/hooks/useVotingPowerRedirect.ts
Labels: collective-rewards

#1253 TOK-869/remove-action-bar-new-account
  src/app/shared/components/BuilderCard/BuilderCardControl.tsx
Labels: collective-rewards, ready-for-qa

#1262 TOK-900/fix-backing-column-builder-table
  src/app/builders/components/Table/BuilderDataRow.tsx
  src/app/builders/components/Table/BuildersTable.tsx
  src/app/builders/hooks/useGetBuilderRewardsSummary.tsx
  src/app/collective-rewards/types.ts
  src/app/my-rewards/backers/components/Table/BackerRewardsTable.tsx
Labels: collective-rewards, ready-for-qa

#1270 TOK-892/update-to-node-24
  .github/workflows/booster-deactivate.yaml
  .github/workflows/booster-schedule.yaml
  .github/workflows/booster.yaml
  .nvmrc
  Dockerfile
  README.md
  package-lock.json
  package.json
Labels: collective-rewards, dao

#1254 TOK-884/cr-estimated-rewards
  src/app/backing/BackingPage.tsx
  src/app/backing/components/AllocationInput/AllocationInput.tsx
  src/app/builders/components/Table/BuilderDataRow.tsx
  src/app/collective-rewards/components/ClaimRewardModal/ClaimRewardsModal.tsx
  src/app/collective-rewards/components/ClaimRewardModal/ClaimRewardsModalView.tsx
  src/app/collective-rewards/components/EstimatedRewards/EstimatedRewards.tsx
  src/app/collective-rewards/components/RewardsMetrics/RewardsMetrics.tsx
  src/app/collective-rewards/components/TotalRewardsDistributed/TotalRewardsDistributed.tsx
  src/app/collective-rewards/rewards/utils/formatter.test.ts
  src/app/collective-rewards/rewards/utils/formatter.ts
  src/app/home/components/collective-balances-section/index.tsx
  src/app/my-rewards/backers/components/Table/BackerRewardsDataRow.tsx
  src/app/my-rewards/backers/hooks/useBackerEstimatedRewards.tsx
  src/app/my-rewards/backers/hooks/useBackerTotalEarned.tsx
  src/app/my-rewards/backers/hooks/useBackerUnclaimedRewards.tsx
  src/app/my-rewards/backers/hooks/useBackersEstimatedRewards.tsx
  src/app/my-rewards/builder/hooks/useGetBuilderAllTimeRewards.ts
  src/app/my-rewards/builder/hooks/useGetBuilderEstimatedRewards.ts
  src/app/my-rewards/builder/hooks/useGetBuilderLastCycleRewards.tsx
  src/app/my-rewards/builder/hooks/useGetBuilderUnclaimedRewards.ts
  src/app/my-rewards/utils.ts
  src/app/treasury/sections/MetricsSection.tsx
  src/app/treasury/sections/TabsSection.tsx
  src/app/user/Balances/BalanceInfoForUser.tsx
  src/app/user/Stake/StakingContext.tsx
  src/app/user/my-holdings/components/backing/MyBacking.tsx
  src/app/user/my-holdings/components/backing/UnclaimedRewardsMetric.tsx
  src/lib/utils/utils.test.ts
  src/lib/utils/utils.ts
Labels: collective-rewards

#1277 TOK-886/querying-graphql
  src/app/collective-rewards/rewards/backers/actions/fetchBackerStakingHistory.ts
  src/app/collective-rewards/rewards/backers/hooks/useGetBackerStakingHistory.ts
  src/app/collective-rewards/rewards/backers/index.ts
  src/app/collective-rewards/shared/actions/fetchABIData.ts
  src/app/collective-rewards/shared/hooks/useGetABIWithGraph.ts
  src/app/proposals/actions/proposalsAction.ts
  src/lib/constants.ts
Labels: collective-rewards

#1275 DAO-1400: Update “Quorum” column display when proposal table is filtered
  src/app/proposals/components/LatestProposalsTable.tsx
  src/app/proposals/components/table-columns/VotesColumn.tsx
Labels: dao

#1257 Tok 875/allocation bar overlaps and style
  src/app/backing/components/AllocationBar/AllocationBar.tsx
  src/app/backing/components/AllocationBar/AllocationBarDragHandle.tsx
  src/app/backing/components/AllocationBar/AllocationBarResizeHandle.tsx
  src/app/backing/components/AllocationBar/AllocationBarSegment.tsx
Labels: collective-rewards

#1291 DAO-1456: My Holdings page shows “RIF” label instead of “tRIF” when disconnected in testnet
  src/app/home/components/collective-balances-section/index.tsx
Labels: dao

#1251 DAO-1407 Add “Add to Wallet” functionality for tokens in My Holdings screen
  src/app/communities/nft/[address]/_components/AddToWalletButton.tsx
  src/app/communities/nft/[address]/utilsClient.ts
  src/app/user/Balances/BalanceInfoForUser.tsx
  src/shared/utils.ts
Labels: dao

#1283 TOK-819: naming refactor and stories fix
  src/app/builders/components/Table/BuilderDataRow.tsx
  src/app/builders/components/Table/BuilderHeaderRow.tsx
  src/app/builders/components/Table/BuilderTable.config.ts
  src/app/builders/components/Table/BuildersTable.tsx
  src/app/builders/components/Table/Cell/AllocationCell/index.ts
  src/app/builders/components/Table/Cell/BackingShareCell/BackingShareCell.stories.tsx
  src/app/builders/components/Table/Cell/BackingShareCell/BackingShareCell.tsx
  src/app/builders/components/Table/Cell/BackingShareCell/index.ts
  src/app/builders/components/Table/TableColumnDropdown/TableColumnDropdown.stories.tsx
Labels: collective-rewards

#1289 DAO-1401 Will now fetch ENS DOMAIN (RNS) from blockscout in the deleg…
  .env.cr.qa
  .env.dao.qa
  .env.dev
  .env.mainnet
  .env.release-candidate-mainnet
  .env.release-candidate-testnet
  .env.testnet.local
  src/app/delegate/contexts/DelegateContext.tsx
  src/app/delegate/lib/types.ts
  src/app/delegate/sections/DelegateContentSection/ConnectedSection.tsx
  src/lib/constants.ts
  src/lib/rns.ts
  src/shared/hooks/useGetExternalDelegatedAmount.ts
Labels: dao

#1299 DAO-1404: add info to create proposal pages
  src/app/proposals/new/details/activation/page.tsx
  src/app/proposals/new/details/components/ProposalInfoSidebar.tsx
  src/app/proposals/new/details/components/index.ts
  src/app/proposals/new/details/grants/page.tsx
Labels: dao

#1278 DAO-1414 Add USDRIF for Grant proposal action Asset type (provide choice, price conversion, token logo)
  src/app/proposals/[id]/page.tsx
  src/app/proposals/hooks/useCreateTreasuryTransferProposal.ts
  src/app/proposals/icons/RbtcIcon.tsx
  src/app/proposals/icons/RifIcon.tsx
  src/app/proposals/icons/TokenIcon.tsx
  src/app/proposals/new/details/components/TokenRadioGroup.tsx
  src/app/proposals/new/details/schemas/TokenSchema.ts
  src/app/proposals/new/review/grants/page.tsx
Labels: dao

#1301 TOK-908: removes tables sticky selection
  src/app/builders/components/Table/BuilderDataRow.tsx
  src/app/my-rewards/backers/components/Table/BackerRewardsDataRow.tsx
Labels: collective-rewards, ready-for-qa

#1317 Prevent stacking banner flickering on home screenre rendering before initial data load
  src/app/user/StackingNotifications/StackingNotifications.tsx
Labels: collective-rewards, dao

#1310 refactor: unify footer drawer usage
  src/app/proposals/new/components/ProposalSubfooter.tsx
  src/app/proposals/new/details/activation/page.tsx
  src/app/proposals/new/details/deactivation/page.tsx
  src/app/proposals/new/details/grants/page.tsx
  src/app/proposals/new/review/activation/page.tsx
  src/app/proposals/new/review/deactivation/page.tsx
  src/app/proposals/new/review/grants/page.tsx
  src/components/MainContainer/ContainerDesktop.tsx
  src/components/MainContainer/ContainerMobile.tsx
  src/components/MainContainer/LayoutProvider.tsx
  src/components/MainContainer/drawers/BottomDrawer.tsx
Labels: collective-rewards

#1318 feat: add Next.js Turbopack support with webpack fallback
  next.config.mjs
  package.json
Labels: enhancement, collective-rewards, dao

#1279 DAO-1394 Voting section displays inconsistent state when switching accounts
  src/app/proposals/[id]/page.tsx
  src/app/proposals/hooks/useVoteCast.ts
  src/app/proposals/hooks/useVotingPowerAtSnapshot.ts
Labels: dao

#1256 TOK-874: show proper title for builder and backer
  src/app/communities/components/SectionContainer.tsx
  src/app/user/my-holdings/MyActivityAndBalances.tsx
  src/app/user/my-holdings/hooks/useIsBuilder.ts
Labels: collective-rewards, ready-for-qa

#1333 DAO-1463: Update color of Delegation and Holdings icons
  public/images/sidemenukoto/Delegation.svg
  public/images/sidemenukoto/Holdings.svg
Labels: dao

#1334 DAO-1466: Useful Links - the spacing between Get RIF/rBTC and icons needs to be larger
  src/components/MainContainer/sidebars/usefulLinksData.tsx
Labels: dao

#1336 DAO-1483 Milestone - Implement cat column for milestone
  src/app/proposals/components/table-columns/CategoryColumn.stories.tsx
  src/app/proposals/components/table-columns/CategoryColumn.tsx
  src/app/proposals/components/table-columns/icons/Milestone1.tsx
  src/app/proposals/components/table-columns/icons/Milestone2.tsx
  src/app/proposals/components/table-columns/icons/Milestone3.tsx
  src/app/proposals/components/table-columns/icons/index.ts
  src/app/user/latest-collective/components/LatestProposalCard.tsx
  src/shared/types/types.ts
Labels: dao

#1347 DAO-1472 Standardized primary class to correct implementation. Remove…
  src/theme/default.css
Labels: dao

#1348 DAO-1471 Edited CommunityItemButtonHandler.tsx to properly reflect de…
  src/app/communities/components/CommunityItemButtonHandler.tsx
Labels: dao

#1273 TOK-870: fix allocation sliders
  src/app/backing/BackingPage.tsx
  src/app/backing/components/AllocationInput/AllocationInput.stories.tsx
  src/app/backing/components/AllocationInput/AllocationInput.tsx
  src/app/backing/components/AvailableBackingMetric/AvailableBackingMetric.stories.tsx
  src/app/backing/components/AvailableBackingMetric/AvailableBackingMetric.tsx
  src/app/backing/components/Spotlight/Spotlight.tsx
  src/app/backing/components/TotalBackingMetric/TotalBackingMetric.stories.tsx
  src/app/backing/components/TotalBackingMetric/TotalBackingMetric.tsx
  src/app/backing/components/index.ts
  src/app/shared/components/BuilderCard/BuilderCard.stories.tsx
  src/app/shared/components/BuilderCard/BuilderCard.tsx
  src/app/shared/components/BuilderCard/BuilderCardControl.tsx
  src/app/shared/components/BuildersSpotlight/BuildersSpotlight.tsx
  src/components/TokenAmountDisplay/TokenAmountDisplay.tsx
  src/lib/utils/utils.ts
Labels: collective-rewards, ready-for-qa

#1359 TOK-913: Error while loading data from node
  src/app/collective-rewards/allocations/context/AllocationsContext.tsx
  src/app/collective-rewards/rewards/backers/context/BackerRewardsContext.tsx
  src/app/communities/nft/[address]/CommunityNFTContext.tsx
  src/app/proposals/hooks/useGetProposalsWithGraph.ts
  src/app/services/getProposalsFromTheGraph.ts
Labels: collective-rewards

#1322 TOK-916: add mobile friendly collective rewards
  src/app/collective-rewards/components/BackersCallToAction/BackersCallToAction.tsx
  src/app/collective-rewards/components/Banner/Banner.tsx
  src/app/collective-rewards/components/BuildersCallToAction/BuildersCallToAction.tsx
  src/app/collective-rewards/components/CallToActionCard/CallToActionCard.stories.tsx
  src/app/collective-rewards/components/CallToActionCard/CallToActionCard.tsx
  src/app/collective-rewards/components/CallToActionSection/CallToActionSection.tsx
  src/app/collective-rewards/components/CountMetric/CountMetric.tsx
  src/app/collective-rewards/components/CurrentCycle/CurrentCycle.tsx
  src/app/collective-rewards/components/CycleMetrics/CycleDay.tsx
  src/app/collective-rewards/components/CycleMetrics/CycleEndingOn.tsx
  src/app/collective-rewards/components/CycleMetrics/CycleMetrics.tsx
  src/app/collective-rewards/components/CycleMetrics/CycleNumber.tsx
  src/app/collective-rewards/components/EstimatedRewards/EstimatedRewards.tsx
  src/app/collective-rewards/components/RewardsMetrics/RewardsMetrics.tsx
  src/app/collective-rewards/components/TotalBacking/TotalBacking.tsx
  src/app/collective-rewards/components/TotalRewardsDistributed/TotalRewardsDistributed.tsx
  src/app/shared/components/AnnualBackersIncentives/AnnualBackersIncentives.tsx
  src/components/MainContainer/ContainerMobile.tsx
  src/components/Metric/Metric.tsx
  src/components/TokenAmount/TokenAmount.tsx
  src/components/containers/ActionMetricsContainer.tsx
Labels: collective-rewards, ready-for-qa

#1341 DAO-1486 Fixed DelegateCard.tsx font size.
  src/app/backing/components/BuilderHeader/BuilderHeader.tsx
  src/app/delegate/components/DelegateCard/DelegateCard.tsx
Labels: dao

#1357 DAO-1496 Fixed trbtc proposal creation in dev
  src/app/proposals/new/review/grants/page.tsx
  src/lib/contracts.ts
Labels: dao

#1328 TOK-907/table-selection-deactivated-builders
  src/app/builders/components/Table/BuilderDataRow.tsx
  src/app/builders/components/Table/BuildersTable.tsx
Labels: collective-rewards, ready-for-qa

#1360 DAO-1497 Unify Milestones icon approach
  src/app/proposals/[id]/page.tsx
  src/app/proposals/components/LatestProposalsTable.tsx
  src/app/proposals/components/MilestoneIcon.tsx
  src/app/proposals/components/category/Category.tsx
  src/app/proposals/components/category/CategoryColumn.stories.tsx
  src/app/proposals/components/category/index.ts
  src/app/proposals/components/icons/Milestone1.tsx
  src/app/proposals/components/icons/Milestone2.tsx
  src/app/proposals/components/icons/Milestone3.tsx
  src/app/proposals/components/icons/ToolsIcon.tsx
  src/app/proposals/components/icons/index.ts
  src/app/proposals/components/table-columns/CategoryColumn.tsx
  src/app/proposals/new/review/grants/page.tsx
  src/app/user/latest-collective/components/CreatorRowComponent.tsx
Labels: dao

#1358 DAO-1469, DAO-1470, DAO-1475
  src/app/user/latest-collective/components/CreatorRowComponent.tsx
  src/app/user/latest-collective/components/LatestProposalCard.tsx
Labels: dao

#1364 TOK-923: allow tooltip on mobile
  src/components/Tooltip/Tooltip.tsx
Labels: do not merge

#1303 TOK-895: split proposal page into smaller components
  src/app/proposals/[id]/components/Description.tsx
  src/app/proposals/[id]/components/ProposalDetails.tsx
  src/app/proposals/[id]/components/ProposalProggressBar.tsx
  src/app/proposals/[id]/components/TechnicalDetails.tsx
  src/app/proposals/[id]/components/VotingDetails.tsx
  src/app/proposals/[id]/components/index.ts
  src/app/proposals/[id]/page.tsx
  src/app/proposals/shared/utils.ts
Labels: collective-rewards

#1374 TOK-932: Fix minor defects
  src/app/backing/BackingPage.tsx
  src/app/backing/components/AllocationBar/AllocationBarTooltipContent.tsx
  src/app/backing/components/BuilderAllocationBar/BuilderAllocationBar.tsx
  src/components/Tooltip/Tooltip.tsx
Labels: collective-rewards

#1380 DAO-1498 [Mobile] Intro Modal - Close icon is different
  src/app/user/IntroModal/IntroModalContent.tsx
  src/components/Icons/CloseIconKoto.tsx
  src/components/Modal/Modal.tsx
Labels: dao

#1382 DAO-1514 [Mobile] Delegation Page - Cards should be mobile friendly
  src/app/delegate/components/DelegateCard/DelegateCard.tsx
  src/app/delegate/sections/DelegateContentSection/DelegatesContainer.tsx
Labels: dao

#1340 TOK-775: Create double y-axis chart for collective rewards
  package-lock.json
  package.json
  src/app/collective-rewards/components/CollectiveRewardsChart/ChartTooltipContent.tsx
  src/app/collective-rewards/components/CollectiveRewardsChart/CollectiveRewardsChart.stories.tsx
  src/app/collective-rewards/components/CollectiveRewardsChart/CollectiveRewardsChart.tsx
  src/app/collective-rewards/components/CollectiveRewardsChart/index.ts
  src/app/collective-rewards/components/CurrentCycle/CurrentCycle.tsx
  src/app/collective-rewards/shared/hooks/useMergeSeries.ts
  src/app/collective-rewards/types.ts
  src/app/collective-rewards/utils/chartUtils.ts
Labels: collective-rewards

#1383 DAO-1500 [Mobile] Intro Modal - Continue button alignment
  src/app/user/IntroModal/IntroModalContent.tsx
Labels: dao
