Repository RootstockCollective/dao-frontend, pull requests merged in 2025-07, with the labels that each got.

#1099 DAO-1326 Created Voting Power Container component
  src/app/delegate/components/VotingPowerContainer/VotingPowerCard.tsx
  src/app/delegate/components/VotingPowerContainer/VotingPowerContainer.stories.tsx
  src/app/delegate/components/VotingPowerContainer/VotingPowerContainer.tsx
  src/app/delegate/components/VotingPowerContainer/constants.ts
  src/app/delegate/components/types.ts
Labels: dao

#1101 refactor-tooltip
  src/app/backing/components/ABIFormula.tsx
  src/app/backing/components/Metrics/AnnualBackersIncentivesMetric.tsx
  src/app/backing/components/Metrics/EstimatedRewardsMetric.tsx
  src/app/backing/components/Popovers/ABIPopover.tsx
  src/app/backing/components/Popovers/EstimatedRewardsPopover.tsx
  src/components/IconButton/InfoIconButton.tsx
  src/components/Metric/MetricTitle.tsx
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/index.ts
Labels: collective-rewards

#1111 New-proposal-card
  src/app/proposals/choose/components/card/card.tsx
  src/app/proposals/choose/components/card/data.tsx
  src/app/proposals/choose/components/card/images/activation.png
  src/app/proposals/choose/components/card/images/deactivation.png
  src/app/proposals/choose/components/card/images/standard.png
  src/app/proposals/choose/components/card/index.ts
  src/app/proposals/choose/components/example-card/data.tsx
  src/app/proposals/choose/components/example-card/example-card.tsx
  src/app/proposals/choose/components/example-card/index.ts
  src/app/proposals/choose/components/info-panel/arrow-link.tsx
  src/app/proposals/choose/components/info-panel/data.tsx
  src/app/proposals/choose/components/info-panel/deactivation-footer.tsx
  src/app/proposals/choose/components/info-panel/icons/arrow-icon.tsx
  src/app/proposals/choose/components/info-panel/icons/chat-icon.tsx
  src/app/proposals/choose/components/info-panel/icons/doc-icon.tsx
  src/app/proposals/choose/components/info-panel/icons/kyc-icon.tsx
  src/app/proposals/choose/components/info-panel/index.ts
  src/app/proposals/choose/components/info-panel/info-panel.tsx
  src/app/proposals/choose/page.tsx
  src/app/proposals/choose/types.ts
  src/app/proposals/new/CardButton.tsx
  src/app/proposals/new/CardParagraph.tsx
  src/app/proposals/new/Deactivation.tsx
  src/app/proposals/new/NewProposalCard.stories.tsx
  src/app/proposals/new/NewProposalCard.tsx
  src/app/proposals/new/NewProposalCardExtended.stories.tsx
  src/app/proposals/new/NewProposalCardExtended.tsx
  src/app/proposals/new/images/ChevronIcon.tsx
  src/app/proposals/new/images/DotsOverlayHoriz.tsx
  src/app/proposals/new/images/DotsOverlayVert.tsx
  src/app/proposals/new/images/grant-big.png
  src/app/proposals/new/images/grant.png
  src/app/proposals/new/images/rewards-big.png
  src/app/proposals/new/images/rewards.png
  src/app/proposals/new/layout.tsx
  src/app/proposals/new/newProposalCards.data.tsx
  src/app/proposals/new/page.tsx
  src/app/proposals/new/stepper/ProposalStepper.tsx
  src/app/proposals/new/stepper/StepperProvider.tsx
  src/components/Icons/ArrowUpRightLightIcon.tsx
  src/components/MainContainer/headers/Breadcrumbs.tsx
  src/components/MainContainer/sidebars/SidebarDesktop.tsx
  src/components/ProgressBarNew/colors.ts
  src/shared/walletConnection/components/topPageHeader/pages/ProposalsTopLeftComponent.tsx
Labels: dao

#1070 DAO-1317 Proposal Details Page
  .eslintrc.json
  src/app/proposals/[id]/page.tsx
  src/app/proposals/[id]/types.ts
  src/app/proposals/components/action-details/index.tsx
  src/app/proposals/components/vote-details/VotingDetails.stories.tsx
  src/app/proposals/components/vote-details/VotingDetails.tsx
  src/app/proposals/create/CreateProposalHeaderSection.tsx
  src/app/proposals/create/TreasuryWithdrawProposalForm.tsx
  src/app/proposals/hooks/useGetProposalVotes.ts
  src/app/proposals/hooks/useProposalQuorumAtSnapshot.ts
  src/app/proposals/hooks/useVoteCast.ts
  src/app/proposals/hooks/useVotingPowerAtSnapshot.ts
  src/components/ButtonNew/Button.tsx
  src/components/Modal/VoteProposalModal.tsx
  src/components/NewPopover/index.tsx
  src/components/ShortenAndCopy/ShortenAndCopy.tsx
  src/components/TypographyNew/Typography.tsx
  src/lib/utils/utils.ts
  src/shared/hooks/useVoteOnProposal.ts
  src/shared/types/index.ts
  src/shared/types/types.ts
  src/shared/types/voting.ts
  src/shared/walletConnection/components/ConnectButtonComponent.tsx
  src/shared/walletConnection/types.ts
Labels: dao

#1112 TOK-805: introduce the current cycle section
  src/app/collective-rewards/CollectiveRewardsPage.tsx
  src/app/collective-rewards/components/CurrentCycle/CurrentCycle.tsx
  src/app/collective-rewards/components/CurrentCycle/index.ts
  src/app/collective-rewards/components/CycleMetrics/CycleDay.stories.tsx
  src/app/collective-rewards/components/CycleMetrics/CycleDay.tsx
  src/app/collective-rewards/components/CycleMetrics/CycleEndingOn.stories.tsx
  src/app/collective-rewards/components/CycleMetrics/CycleEndingOn.tsx
  src/app/collective-rewards/components/CycleMetrics/CycleMetrics.tsx
  src/app/collective-rewards/components/CycleMetrics/CycleNumber.stories.tsx
  src/app/collective-rewards/components/CycleMetrics/CycleNumber.tsx
  src/app/collective-rewards/components/CycleMetrics/index.ts
  src/app/collective-rewards/components/EstimatedRewards/EstimatedRewards.tsx
  src/app/collective-rewards/components/EstimatedRewards/index.ts
  src/app/collective-rewards/components/TotalBacking/TotalBacking.stories.tsx
  src/app/collective-rewards/components/TotalBacking/TotalBacking.tsx
  src/app/collective-rewards/components/TotalBacking/index.ts
  src/components/Metric/Metric.tsx
Labels: collective-rewards

#1107 TOK-753/backing-from-builder-page
  src/app/backing/BackingPage.tsx
  src/app/backing/components/AllocationBar/AllocationBar.tsx
  src/app/backing/components/AllocationInput/AllocationInput.tsx
  src/app/backing/components/AvailableBackingMetric/AvailableBackingMetric.tsx
  src/app/backing/components/BackingBanner/BackingBanner.tsx
  src/app/backing/components/BackingInfoTitle/BackingInfoTitle.tsx
  src/app/backing/components/BuilderAllocationBar/BuilderAllocationBar.tsx
  src/app/backing/components/BuilderCard/BackMoreBuildersCard.tsx
  src/app/backing/components/BuilderCard/BuilderCard.stories.tsx
  src/app/backing/components/BuilderCard/BuilderCard.tsx
  src/app/backing/components/BuilderCard/BuilderCardControl.tsx
  src/app/backing/components/BuildersSpotlight/BuildersSpotlight.tsx
  src/app/backing/components/Container/BackingInfoContainer/BackingInfoContainer.tsx
  src/app/backing/components/CurrentBacking/CurrentBacking.tsx
  src/app/backing/components/Metrics/AnnualBackersIncentives.tsx
  src/app/backing/components/Metrics/AnnualBackingIncentives.tsx
  src/app/backing/components/RewardsInfo/RewardsInfo.stories.tsx
  src/app/backing/components/RewardsInfo/RewardsInfo.tsx
  src/app/backing/components/utils.ts
  src/app/collective-rewards/allocations/context/AllocationsContext.tsx
  src/components/Icons/BuildingBrick.tsx
  src/components/Icons/WarningIcon.tsx
  src/components/Icons/index.ts
  src/components/Legend/Legend.tsx
  src/components/MainContainer/LayoutProvider.tsx
  src/components/containers/ActionMetricsContainer.tsx
  src/components/containers/ActionsContainer.tsx
  src/shared/walletConnection/components/ConnectButtonComponent.tsx
Labels: collective-rewards

#1060 feat(builders): add table component
  package-lock.json
  src/app/backing/components/BackingCell/BackingCell.stories.tsx
  src/app/builders/BuilderFilterDropdown.stories.tsx
  src/app/builders/BuilderFilterDropdown.tsx
  src/app/builders/BuildersPage.tsx
  src/app/builders/components/MultipleSelectDropdown/MultipleSelectDropdown.tsx
  src/app/builders/components/Table.tsx
  src/app/builders/components/Table/BuilderDataRow.tsx
  src/app/builders/components/Table/BuilderHeaderRow.stories.tsx
  src/app/builders/components/Table/BuilderHeaderRow.tsx
  src/app/builders/components/Table/BuilderTable.config.ts
  src/app/builders/components/Table/BuilderTable.types.ts
  src/app/builders/components/Table/BuildersTable.tsx
  src/app/builders/components/Table/Cell/ActionCell/ActionCell.stories.tsx
  src/app/builders/components/Table/Cell/ActionCell/ActionCell.tsx
  src/app/builders/components/Table/Cell/ActionCell/index.ts
  src/app/builders/components/Table/Cell/AllocationCell/AllocationCell.stories.tsx
  src/app/builders/components/Table/Cell/AllocationCell/AllocationCell.tsx
  src/app/builders/components/Table/Cell/AllocationCell/index.ts
  src/app/builders/components/Table/Cell/BackersPercentageCell/BackersPercentage.stories.tsx
  src/app/builders/components/Table/Cell/BackersPercentageCell/BackersPercentageCell.tsx
  src/app/builders/components/Table/Cell/BackersPercentageCell/index.ts
  src/app/builders/components/Table/Cell/BackingCell/BackingCell.stories.tsx
  src/app/builders/components/Table/Cell/BackingCell/BackingCell.tsx
  src/app/builders/components/Table/Cell/BackingCell/index.ts
  src/app/builders/components/Table/Cell/BuilderNameCell/BuilderNameCell.stories.tsx
  src/app/builders/components/Table/Cell/BuilderNameCell/BuilderNameCell.tsx
  src/app/builders/components/Table/Cell/BuilderNameCell/index.ts
  src/app/builders/components/Table/Cell/RewardsCell/RewardsCell.stories.tsx
  src/app/builders/components/Table/Cell/RewardsCell/RewardsCell.tsx
  src/app/builders/components/Table/Cell/RewardsCell/index.ts
  src/app/builders/components/Table/Cell/SelectorCell/SelectorCell.stories.tsx
  src/app/builders/components/Table/Cell/SelectorCell/SelectorCell.tsx
  src/app/builders/components/Table/Cell/SelectorCell/index.ts
  src/app/builders/components/Table/SelectorHeaderCell.stories.tsx
  src/app/builders/components/Table/SelectorHeaderCell.tsx
  src/app/builders/components/Table/Table.stories.tsx
  src/app/builders/components/Table/TableColumnDropdown/TableColumnDropdown.stories.tsx
  src/app/builders/components/Table/TableColumnDropdown/TableColumnDropdown.tsx
  src/app/builders/components/Table/index.ts
  src/app/collective-rewards/rewards/builders/hooks/useGetBuildersRewards.ts
  src/app/collective-rewards/rewards/hooks/useGetLastCycleDistribution.ts
  src/app/collective-rewards/shared/hooks/useGetEstimatedRewardsPct.ts
  src/components/TableNew/ActionCell.tsx
  src/components/TableNew/TableHeaderCell.tsx
  src/shared/context/TableContext/TableProvider.tsx
  src/shared/context/TableContext/tableReducer.ts
  src/shared/context/TableContext/types.ts
Labels: collective-rewards

#1124 Tok 791/claim rewards modal
  package-lock.json
  package.json
  src/app/collective-rewards/components/ClaimRewardModal/ClaimRewardRadioGroup.stories.tsx
  src/app/collective-rewards/components/ClaimRewardModal/ClaimRewardRadioGroup.tsx
  src/app/collective-rewards/components/ClaimRewardModal/ClaimRewardRadioOption.stories.tsx
  src/app/collective-rewards/components/ClaimRewardModal/ClaimRewardRadioOption.tsx
  src/app/collective-rewards/components/ClaimRewardModal/ClaimRewardsModal.tsx
  src/app/collective-rewards/components/ClaimRewardModal/ClaimRewardsModalView.stories.tsx
  src/app/collective-rewards/components/ClaimRewardModal/ClaimRewardsModalView.tsx
  src/app/collective-rewards/components/ClaimRewardModal/types.ts
Labels: collective-rewards

#1138 TOK-818: improves builder state tooltips
  src/app/builders/BuilderFilterDropdown.tsx
  src/app/builders/components/Table/BuilderTable.config.ts
  src/app/builders/components/Table/BuildersTable.tsx
  src/app/builders/components/Table/Cell/BuilderNameCell/BuilderNameCell.stories.tsx
  src/app/builders/components/Table/Cell/BuilderNameCell/BuilderNameCell.tsx
  src/app/collective-rewards/utils/isBuilderOperational.ts
Labels: collective-rewards

#1140 Dao 1379 My Balance section
  .env.cr.qa
  .env.dao.qa
  .env.dev
  .env.mainnet
  .env.release-candidate-mainnet
  .env.release-candidate-testnet
  .env.testnet.local
  public/images/usdrif-logo.png
  src/app/user/Balances/BalanceInfoForUser.tsx
  src/app/user/Balances/BalancesSection.tsx
  src/app/user/Balances/RenderTokenPrice.tsx
  src/app/user/Balances/RenderTokenSymbol.tsx
  src/app/user/Balances/RenderTotalBalance.tsx
  src/app/user/Balances/StakeRIFCell.tsx
  src/app/user/Balances/UnStakeRIFCell.tsx
  src/app/user/Balances/balanceUtils.ts
  src/app/user/Balances/context/BalancesContext.tsx
  src/app/user/Balances/hooks/useGetAddressBalances.ts
  src/app/user/Balances/hooks/useGetAddressTokens.ts
  src/app/user/api/tokens/route.ts
  src/components/ButtonNew/Button.tsx
  src/components/Icons/MoneyIconKoto.tsx
  src/components/Icons/index.ts
  src/components/TokenImage/TokenImage.tsx
  src/lib/constants.ts
  src/lib/contracts.ts
Labels: dao

#1137 DAO-1380 HomeScreen - Connected (Feature) - The Latest in the Collective
  src/app/backing/components/AvailableBackingMetric/AvailableBackingMetric.tsx
  src/app/delegate/components/VotingPowerContainer/VotingPowerCard.tsx
  src/app/dummy-home/page.tsx
  src/app/proposals/ProposalsFromTheGraph.tsx
  src/app/proposals/[id]/page.tsx
  src/app/proposals/components/LatestProposalsTable.tsx
  src/app/proposals/components/table-columns/CategoryColumn.tsx
  src/app/proposals/components/table-columns/TimeColumn.tsx
  src/app/proposals/components/table-columns/VotesColumn.tsx
  src/app/proposals/components/vote-details/VotingDetails.tsx
  src/app/proposals/components/voting-power-with-action/index.tsx
  src/app/proposals/hooks/useGetProposalsWithGraph.ts
  src/app/proposals/hooks/useProposalListData.ts
  src/app/proposals/hooks/useVotingPower.ts
  src/app/proposals/shared/utils.ts
  src/app/user/latest-collective/index.tsx
  src/components/BalanceInfo/BalanceInfo.tsx
  src/components/IconButton/InfoIconButton.tsx
  src/components/Icons/KotoQuestionMarkIcon.tsx
  src/components/Icons/index.ts
  src/components/Icons/types.ts
  src/components/MainContainer/footers/FooterDesktop.tsx
  src/components/MainContainer/footers/FooterMobile.tsx
  src/components/MainContainer/sidebars/menuData.tsx
  src/components/Separators/SmallLineSeparator/index.tsx
  src/components/SingleSelectDropdown/SingleSelectDropdown.tsx
  src/shared/walletConnection/components/topPageHeader/pages/ProposalDetailTopLeftComponent.tsx
Labels: dao

#1152 TOK-828: no rewards page
  src/app/collective-rewards/rewards/hooks/useIsBacker.ts
  src/app/collective-rewards/settings/builder/context/BuilderSettingsContext.tsx
  src/app/my-rewards/MyRewardsPage.tsx
  src/app/my-rewards/components/NonBacker.tsx
  src/app/my-rewards/components/index.ts
  src/app/my-rewards/page.tsx
  src/components/Icons/v3design/HeartBroken.tsx
  src/components/Icons/v3design/Icons.stories.tsx
  src/components/Icons/v3design/index.ts
Labels: collective-rewards

#1144 TOK-793/backer-rewards-table
  src/app/builders/components/MultipleSelectDropdown/MultipleSelectDropdown.tsx
  src/app/builders/components/Table/BuilderDataRow.tsx
  src/app/builders/components/Table/BuilderHeaderRow.tsx
  src/app/builders/components/Table/BuilderTable.config.ts
  src/app/builders/components/Table/TableColumnDropdown/TableColumnDropdown.stories.tsx
  src/app/builders/components/Table/TableColumnDropdown/TableColumnDropdown.tsx
  src/app/collective-rewards/rewards/backers/context/BackerRewardsContext.tsx
  src/app/collective-rewards/rewards/backers/hooks/useGetBackerRewards.ts
  src/app/my-rewards/MyRewardsPage.tsx
  src/app/my-rewards/backers/components/BackerRewards/BackerRewards.tsx
  src/app/my-rewards/backers/components/BackerRewards/index.ts
  src/app/my-rewards/backers/components/Table/BackerRewardsDataRow.tsx
  src/app/my-rewards/backers/components/Table/BackerRewardsHeaderRow.tsx
  src/app/my-rewards/backers/components/Table/BackerRewardsTable.config.ts
  src/app/my-rewards/backers/components/Table/BackerRewardsTable.tsx
  src/app/my-rewards/backers/components/Table/BackerRewardsTableContainer.tsx
  src/app/my-rewards/backers/components/Table/index.ts
  src/shared/context/TableContext/TableActionsContext.tsx
  src/shared/context/TableContext/TableContext.tsx
Labels: collective-rewards

#1154 DAO-1357 Added Enkrypt as supported wallet
  src/app/providers/ContextProviders.tsx
Labels: dao

#1119 TOK-792/backer-rewards-metrics-section
  src/app/api/backers/[backer]/metrics/rbi/context/route.ts
  src/app/collective-rewards/CollectiveRewardsPage.tsx
  src/app/collective-rewards/rewards/backers/context/BackerRewardsContext.tsx
  src/app/my-rewards/MyRewardsPage.tsx
  src/app/my-rewards/backers/components/BackerABI.tsx
  src/app/my-rewards/backers/components/BackerEstimatedRewards.tsx
  src/app/my-rewards/backers/components/BackerRewards.tsx
  src/app/my-rewards/backers/components/BackerRewardsMetrics.tsx
  src/app/my-rewards/backers/components/BackerRewardsNotConnected.tsx
  src/app/my-rewards/backers/components/BackersEstimatedRewards.tsx
  src/app/my-rewards/backers/components/RBI.tsx
  src/app/my-rewards/backers/components/Table/BackerRewardsTableContainer.tsx
  src/app/my-rewards/backers/components/TotalEarned.tsx
  src/app/my-rewards/backers/components/UnclaimedRewards.tsx
  src/app/my-rewards/backers/hooks/index.ts
  src/app/my-rewards/backers/hooks/useBackerEstimatedRewards.tsx
  src/app/my-rewards/backers/hooks/useBackerTotalEarned.tsx
  src/app/my-rewards/backers/hooks/useBackerUnclaimedRewards.tsx
  src/app/my-rewards/backers/hooks/useBackersEstimatedRewards.tsx
  src/app/my-rewards/builder/components/BuilderRewards.tsx
  src/app/my-rewards/components/RewardCard.tsx
  src/app/my-rewards/types.ts
  src/app/shared/components/AnnualBackersIncentives/AnnualBackersIncentives.tsx
  src/app/shared/components/AnnualBackersIncentives/index.ts
  src/components/Switch/Switch.tsx
Labels: collective-rewards

#1158 Review the UpdateBackerRewards% modal
  src/app/my-rewards/builder/components/BuilderRewards.tsx
  src/app/my-rewards/builder/components/UpdateBackerRewardModal/UpdateBackerRewardModal.tsx
  src/app/my-rewards/builder/components/UpdateBackerRewardModal/UpdateBackerRewardViewModal.stories.tsx
  src/app/my-rewards/builder/components/UpdateBackerRewardModal/UpdateBackerRewardViewModal.tsx
Labels: collective-rewards

#1156 DAO-1377 Added menuData for both connected and not connected states
  src/components/MainContainer/headers/HeaderMobile.tsx
  src/components/MainContainer/sidebars/SidebarDesktop.tsx
  src/components/MainContainer/sidebars/SidebarMobile.tsx
  src/components/MainContainer/sidebars/menuData.tsx
Labels: dao

#1178 DAO-1410: Adjust the Create builder Rewards text
  src/app/proposals/new/components/CardParagraph.tsx
  src/app/proposals/new/components/NewProposalCard.tsx
  src/app/proposals/new/components/NewProposalCardExtended.tsx
  src/app/proposals/new/newProposalCards.data.tsx
Labels: dao

#1172 DAO-1408 My Holdings table in Treasury page shows incorrect default sort direction on Holder column
  src/app/treasury/sections/holders-section/index.tsx
Labels: dao

#1174 TOK-824: use the top 5 builders to calculate the weighted avg pct
  src/app/collective-rewards/shared/hooks/useGetABI.ts
Labels: collective-rewards

#1168 TOK-838: Allocation bar adjustments
  src/app/backing/BackingPage.tsx
  src/app/backing/components/AllocationBar/AllocationBarSegment.tsx
  src/app/backing/components/AllocationInput/AllocationInput.tsx
  src/app/backing/components/BuilderAllocationBar/BuilderAllocationBar.tsx
  src/app/backing/components/CurrentBacking/CurrentBacking.tsx
  src/app/backing/components/Spotlight/Spotlight.tsx
  src/app/backing/components/StickySlider/StickySlider.tsx
  src/app/builders/components/Table/BuildersTable.tsx
  src/app/shared/components/BuilderCard/BuilderCard.tsx
  src/app/shared/components/BuilderCard/BuilderCardControl.tsx
Labels: collective-rewards

#1184 TOK-846: Backer/Builder rewards claim flow
  src/app/collective-rewards/components/ClaimRewardModal/ClaimRewardsModal.tsx
  src/app/my-rewards/backers/components/UnclaimedRewards.tsx
  src/app/my-rewards/builder/components/UnclaimedRewards.tsx
  src/app/my-rewards/builder/hooks/useGetBuilderUnclaimedRewards.ts
Labels: collective-rewards

#1186 DAO-1413 View details in explorer changed to view in explorer
  src/app/treasury/components/AddressLink.tsx
Labels: dao

#1183 Add the become a builder banner to the Builders page
  src/app/builders/BuildersPage.tsx
  src/app/builders/components/BecomeBuilderBanner/BecomeBuilderBanner.stories.tsx
  src/app/builders/components/BecomeBuilderBanner/BecomeBuilderBanner.tsx
Labels: collective-rewards

#1190 TOK-855: add the banners for CR
  src/app/user/StackingNotifications/StackingNotifications.tsx
  src/app/user/StackingNotifications/configs.tsx
  src/app/user/StackingNotifications/constants.tsx
  src/app/user/StackingNotifications/hooks/useGetBuilderState.tsx
  src/app/user/StackingNotifications/hooks/useHasAvailableForBacking.tsx
  src/app/user/StackingNotifications/types.ts
Labels: collective-rewards

#1204 fix: show random builders in home page
  src/app/shared/components/BuilderCard/BuilderCard.tsx
  src/app/shared/components/BuildersSpotlight/BuildersSpotlight.tsx
  src/app/user/latest-collective/index.tsx
Labels: collective-rewards

#1181 fix: sidebar map unique key
  src/components/MainContainer/sidebars/SidebarDesktop.tsx
  src/components/MainContainer/sidebars/SidebarMobile.tsx
Labels: dao

#1191 feat: adds conditional tooltip and button
  src/app/backing/BackingPage.tsx
  src/app/backing/components/Popovers/ConnectPopover.stories.tsx
  src/app/backing/components/Popovers/ConnectPopover.tsx
  src/app/builders/components/Table/BuilderDataRow.tsx
  src/app/builders/components/Table/Cell/BuilderNameCell/BuilderNameCell.tsx
  src/app/collective-rewards/components/ClaimRewardModal/ClaimRewardsModalView.tsx
  src/app/components/Button/AlwaysEnabledButton/AlwaysEnabledButton.stories.tsx
  src/app/components/Button/AlwaysEnabledButton/AlwaysEnabledButton.tsx
  src/app/components/Button/AlwaysEnabledButton/index.ts
  src/app/components/Button/ConnectButton/ConnectButton.tsx
  src/app/components/Tooltip/ConditionalTooltip/ConditionalTooltip.stories.tsx
  src/app/components/Tooltip/ConditionalTooltip/ConditionalTooltip.tsx
  src/app/components/Tooltip/ConditionalTooltip/index.ts
  src/app/components/Tooltip/ConnectTooltip/ConnectTooltip.tsx
  src/app/components/Tooltip/ConnectTooltip/ConnectTooltipContent.tsx
  src/app/components/index.ts
  src/app/my-rewards/backers/components/Table/BackerRewardsDataRow.tsx
  src/app/my-rewards/builder/components/UpdateBackerRewardModal/UpdateBackerRewardViewModal.tsx
  src/app/shared/components/BuilderCard/BuilderCard.tsx
  src/app/user/my-holdings/components/backing/UnclaimedRewardsMetric.tsx
  src/components/ButtonNew/Button.tsx
  src/shared/walletConnection/components/ConnectButtonComponent.tsx
Labels: collective-rewards

#1192 fix/table-builder-states
  src/app/backing/components/AvailableBackingMetric/AvailableBackingMetric.tsx
  src/app/builders/components/Table/BuildersTable.tsx
  src/app/builders/components/Table/BuildersTableContainer.tsx
  src/app/builders/components/Table/Cell/BuilderNameCell/BuilderNameCell.tsx
  src/app/builders/components/Table/utils.ts
  src/app/collective-rewards/utils/isBuilderOperational.ts
  src/components/RifRbtcTooltip/RifRbtcTooltip.tsx
Labels: collective-rewards

#1206 style: fix tooltip padding
  src/components/IconButton/InfoIconButton.tsx
Labels: collective-rewards

#1209 style: fix table row builder cell selected state
  src/app/builders/components/Table/BuilderDataRow.tsx
  src/app/builders/components/Table/Cell/BuilderNameCell/BuilderNameCell.tsx
Labels: collective-rewards

#1213 fix(home): on back builder btn nav to backing
  src/app/shared/components/BuilderCard/BuilderCard.tsx
Labels: collective-rewards

#1203 Communities-details-page
  src/app/communities/communityUtils.tsx
  src/app/communities/components/BoostedLabelKoto.tsx
  src/app/communities/nft/[address]/CommunityNFTContext.tsx
  src/app/communities/nft/[address]/_components/AddToWalletButton.tsx
  src/app/communities/nft/[address]/_components/ClaimItButton.tsx
  src/app/communities/nft/[address]/_components/NFTMiscData.tsx
  src/app/communities/nft/[address]/_components/NftCard.tsx
  src/app/communities/nft/[address]/_components/NftHolderTableCell.tsx
  src/app/communities/nft/[address]/_components/NftHoldersTable.tsx
  src/app/communities/nft/[address]/_sections/CommunityInfoHeader.tsx
  src/app/communities/nft/[address]/_sections/MembershipNFTSection.tsx
  src/app/communities/nft/[address]/_sections/NftHoldersSection.tsx
  src/app/communities/nft/[address]/_sections/UserMemberSection.tsx
  src/app/communities/nft/[address]/_sections/ViewIconHandler.tsx
  src/app/communities/nft/[address]/page.tsx
  src/app/communities/nft/[address]/utilsClient.ts
  src/components/BreadcrumbsNew/Breadcrumbs.tsx
  src/components/ImageMask/ImageMask.stories.tsx
  src/components/ImageMask/ImageMask.tsx
  src/components/ImageMask/index.ts
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/PaginationPageSizeSelector.tsx
  src/shared/hooks/useFetchNftHolders.ts
  src/shared/hooks/usePagination.ts
Labels: urgent, dao

#1214 fix: new cycle strarting soon text
  src/app/user/StackingNotifications/constants.tsx
Labels: collective-rewards

#1219 Dao 1430
  src/app/proposals/[id]/page.tsx
  src/app/proposals/new/review/activation/page.tsx
  src/app/proposals/new/review/grants/page.tsx
  src/app/proposals/shared/utils.test.ts
  src/app/proposals/shared/utils.ts
Labels: dao

#1223 TOK-866: replace hard-coded metrics with real ones
  src/app/backing/components/Metrics/EstimatedRewardsMetric.tsx
  src/app/builders/components/ActiveBuilders.tsx
  src/app/builders/components/EstimatedRewards.tsx
  src/app/builders/components/Metrics.tsx
  src/app/builders/components/TotalBacking.tsx
  src/app/collective-rewards/components/ActiveBackers/ActiveBackers.tsx
  src/app/collective-rewards/components/ActiveBuilders/ActiveBuilders.tsx
  src/app/collective-rewards/components/CallToActionSection/CallToActionSection.tsx
  src/app/collective-rewards/components/TotalBacking/TotalBacking.tsx
  src/app/collective-rewards/shared/hooks/useGetActiveBuildersCount.ts
Labels: collective-rewards

#1225 fix: show estimated rewards on BuilderCard
  src/app/backing/components/RewardsInfo/RewardsInfo.tsx
  src/app/backing/components/Spotlight/Spotlight.tsx
  src/components/RifRbtcTooltip/RifRbtcTooltip.tsx
Labels: collective-rewards

#1226 fix(backing): bulder alloc card slider label
  src/app/backing/components/AllocationInput/AllocationInput.tsx
Labels: collective-rewards

#1227 fix: make the slider more stable
  src/app/backing/components/AllocationInput/AllocationInput.tsx
  src/app/backing/hooks/useExitOnOutsideClick.ts
  src/app/shared/components/BuilderCard/BuilderCard.tsx
Labels: collective-rewards

#1245 DAO-1437 Fixed balances in the collective balances
  src/app/home/components/collective-balances-section/index.tsx
  src/app/user/Balances/balanceUtils.ts
Labels: dao

#1236 Tok 861/table alignment
  src/app/builders/components/Table/BuilderHeaderRow.tsx
  src/app/my-rewards/backers/components/Table/BackerRewardsHeaderRow.tsx
Labels: collective-rewards
