Repository RootstockCollective/dao-frontend, pull requests merged in 2025-09, with the labels that each got.

#1363 TOK-923: show tooltip on click on mobile
  src/components/Tooltip/Tooltip.tsx
Labels: collective-rewards

#1392 DAO-1512: HeroComponent with responsive design
  src/app/user/components/top-hero/index.tsx
  src/components/Button/Button.tsx
  src/components/Expandable/Expandable.tsx
  src/components/Expandable/ExpandableComponent.tsx
  src/components/Expandable/ExpandableContent.tsx
  src/components/Expandable/ExpandableContext.tsx
  src/components/Expandable/ExpandableFooter.tsx
  src/components/Expandable/ExpandableHeader.tsx
  src/components/Expandable/ExpandableTrigger.tsx
  src/components/Expandable/index.ts
  src/components/HeroComponent/HeroComponent.stories.tsx
  src/components/HeroComponent/HeroComponent.tsx
  src/components/HeroComponent/HeroComponentDesktop.tsx
  src/components/HeroComponent/HeroComponentMobile.tsx
  src/components/Icons/KotoChevronDownIcon.tsx
  src/components/Icons/index.ts
  src/shared/hooks/useImagePreloader.ts
  src/shared/hooks/useIsDesktop.ts
Labels: dao

#1408 DAO - 1525 [Mobile] Proposal List Page - Latest Proposals Header should scroll with user (sticky)
  src/app/proposals/components/LatestProposalsTable.tsx
  src/components/MainContainer/ContainerMobile.tsx
  src/shared/hooks/index.ts
  src/shared/hooks/useStickyHeader.ts
Labels: dao

#1421 TOK-947: Add responsive design on Builders banner
  src/app/builders/components/BecomeBuilderBanner/BecomeBuilderBanner.tsx
Labels: collective-rewards, ready-for-qa

#1418 TOK-946: top metrics mobile
  src/app/builders/components/ActiveBuilders.tsx
  src/app/builders/components/EstimatedRewards.tsx
  src/app/builders/components/Metrics.tsx
  src/app/builders/components/TotalBacking.tsx
  src/components/Metric/Metric.tsx
  src/components/Metric/MetricTitle.tsx
  src/components/containers/MetricsContainer.tsx
Labels: collective-rewards, ready-for-qa

#1426 TOK-949: Builders Table filter modal - mobile
  src/app/builders/components/Table/BuilderFilterDropdown/BuilderFilterDropdown.tsx
  src/app/builders/components/Table/BuilderFilterDropdown/constants.ts
  src/app/builders/components/Table/BuildersTable.tsx
  src/app/builders/components/Table/BuildersTableContainer.tsx
  src/app/builders/components/Table/BuildersTableTitle.tsx
  src/app/builders/components/Table/MobileCurrentFilter.tsx
  src/app/builders/components/Table/MobileFilterModal.tsx
  src/app/builders/components/Table/utils/builderFilters.ts
  src/app/proposals/components/filter/FilterRadioItem.stories.tsx
  src/app/proposals/components/filter/FilterRadioItem.tsx
  src/app/proposals/components/filter/FilterSideBar.tsx
  src/components/Icons/FilterIcon.tsx
  src/components/SelectableItem/SelectableItem.stories.tsx
  src/components/SelectableItem/SelectableItem.tsx
  src/components/SelectableItem/index.ts
  src/shared/context/TableContext/tableReducer.ts
  src/shared/hooks/useScrollLock.ts
Labels: collective-rewards, ready-for-qa

#1407 DAO-1522 [Mobile] Proposal List Page - Edit ProposalsSummary to adapt to mobile
  src/app/delegate/components/VotingPowerContainer/VotingPowerCard.tsx
  src/app/proposals/ProposalsFromTheGraph.tsx
  src/app/proposals/ProposalsSummary.tsx
Labels: dao

#1429 Fix invalid number big,js
  src/app/proposals/hooks/useGetProposalsWithGraph.ts
Labels: dao

#1439 DAO-1561 Adjusted treasury holders section to have mobile design
  src/app/treasury/components/MobileHolderCard.stories.tsx
  src/app/treasury/components/MobileHolderCard.tsx
  src/app/treasury/sections/holders-section/components/HolderCard.tsx
  src/app/treasury/sections/holders-section/components/MobileHolderContainer.tsx
  src/app/treasury/sections/holders-section/components/index.ts
  src/app/treasury/sections/holders-section/index.tsx
Labels: dao

#1395 DAO-1492 [AI] Add holder image if exists for reclaim, delegate, and w…
  src/app/backing/components/BuilderHeader/BuilderHeader.tsx
  src/app/delegate/components/DelegateCard/DelegateCard.tsx
  src/app/delegate/components/DelegateModal/DelegateModal.tsx
  src/app/delegate/contexts/DelegateContext.tsx
  src/app/delegate/lib/types.ts
  src/app/delegate/sections/DelegateContentSection/ConnectedSection.tsx
  src/app/delegate/sections/DelegateContentSection/DelegatesContainer.tsx
  src/components/IpfsAvatar/IpfsAvatar.tsx
  src/components/IpfsAvatar/index.ts
Labels: dao

#1441 DAO-1566 Made community page mobile friendly
  src/app/communities/CommunityItem.tsx
  src/app/communities/components/ImageDebris.tsx
  src/app/communities/components/ResponsiveCommunityItemHOC.tsx
  src/app/communities/components/SectionContainer.tsx
  src/app/communities/hooks/usePixelExtractor.ts
  src/app/communities/page.tsx
Labels: dao

#1427 TOK-948/mobile-builders-spotlight
  src/app/backing/BackingPage.tsx
  src/app/backing/components/Spotlight/Spotlight.tsx
  src/app/collective-rewards/user/context/BuilderContext.tsx
  src/app/shared/components/BuilderCard/BuilderCard.tsx
  src/app/shared/components/BuilderCard/BuilderCardControl.tsx
  src/app/shared/components/BuilderCard/WindshieldWiperAnimation.tsx
  src/app/shared/components/BuildersSpotlight/BuildersSpotlight.tsx
  src/app/shared/components/BuildersSpotlight/index.ts
  src/app/shared/components/SpotlightBuildersGrid/SpotlightBuildersGrid.tsx
  src/app/shared/components/SpotlightBuildersGrid/index.ts
  src/app/user/latest-collective/index.tsx
  src/theme/default.css
Labels: collective-rewards, ready-for-qa

#1425 Tok 839: make non-op builders not editable
  src/app/backing/components/AllocationBar/AllocationBar.stories.tsx
  src/app/backing/components/AllocationBar/AllocationBar.tsx
  src/app/backing/components/AllocationBar/AllocationBarDragHandle.tsx
  src/app/backing/components/AllocationBar/AllocationBarResizeHandle.tsx
  src/app/backing/components/AllocationBar/AllocationBarSegment.tsx
  src/app/backing/components/AllocationBar/AllocationBarTooltip.tsx
  src/app/backing/components/AllocationBar/AllocationBarTooltipContent.tsx
  src/app/backing/components/AllocationBar/BarTooltipContent.stories.tsx
  src/app/backing/components/AllocationBar/BarTooltipContent.tsx
  src/app/backing/components/AllocationBar/ResizeHandle.tsx
  src/app/backing/components/AllocationBar/types.ts
  src/app/backing/components/AllocationBar/utils.ts
  src/app/backing/components/BuilderAllocationBar/BuilderAllocationBar.tsx
  src/components/Circle/Circle.tsx
  src/components/Legend/Legend.stories.tsx
  src/components/Legend/Legend.tsx
Labels: collective-rewards

#1431 DAO-1553 Enable onramp
  src/app/providers/ContextProviders.tsx
  src/shared/walletConnection/connection/DisconnectWorkflowPresentation.tsx
Labels: do not merge

#1454 TOK-969/subgraph-deployment
  .env.cr.qa
  .env.dao.qa
  .env.dev
  .env.mainnet
  .env.release-candidate-mainnet
  .env.release-candidate-testnet
  .env.testnet.local
  src/app/collective-rewards/shared/actions/fetchABIData.ts
Labels: collective-rewards

#1446 feat(contributors): add contributors route
  src/app/api/contributors/v1/route.ts
  src/app/delegate/actions/delegateAction.ts
  src/app/proposals/shared/types/index.ts
Labels: dao

#1412 DAO-1524 [Mobile] Proposal List Page - Filters overlay
  src/app/proposals/components/LatestProposalsTable.tsx
  src/app/proposals/components/filter/ActiveFiltersDisplay.tsx
  src/app/proposals/components/filter/FilterChip.tsx
  src/app/proposals/components/filter/FilterSideBar.stories.tsx
  src/app/proposals/components/filter/FilterSideBar.tsx
  src/app/proposals/components/filter/filterOptions.ts
  src/app/proposals/components/filter/types.ts
  src/app/proposals/components/filter/useProposalFilters.tsx
  src/components/SelectableItem/SelectableItem.tsx
Labels: dao

#1476 DAO-1419: Search bar should always be visible in proposals for mobile
  src/app/proposals/components/LatestProposalsTable.tsx
  src/app/proposals/components/filter/useProposalFilters.tsx
  src/components/DebounceSearch/DebounceSearch.tsx
Labels: dao

#1475 DAO-1574: [Mobile] Delegation Page adjustments
  src/app/delegate/components/DelegateCard/DelegateCard.tsx
  src/app/delegate/sections/DelegateContentSection/DelegatesContainer.tsx
  src/app/delegate/sections/DelegateContentSection/NotConnectedSection.tsx
  src/components/Button/Button.tsx
  src/components/Expandable/ExpandableTrigger.tsx
  src/components/HeroComponent/HeroComponentDesktop.tsx
  src/components/HeroComponent/HeroComponentMobile.tsx
  src/shared/walletConnection/components/ConnectButtonComponent.tsx
Labels: dao
