Repository RootstockCollective/dao-frontend, pull requests merged in 2025-06, with the labels that each got.

#1025 build: update the graphs deployment ids
  .env.cr.qa
  .env.dao.qa
  .env.dev
  .env.mainnet
  .env.release-candidate
Labels: collective-rewards

#1013 TOK-756: improve feature flags
  .env.cr.qa
  .env.testnet.local
  src/app/backing/page.tsx
  src/app/providers/ContextProviders.tsx
  src/config/features.conf.ts
  src/lib/constants.ts
  src/shared/context/FeatureFlag/FeatureFlagContext.test.tsx
  src/shared/context/FeatureFlag/FeatureFlagContext.tsx
  src/shared/context/FeatureFlag/flags.ts
  src/shared/context/FeatureFlag/flags.utils.test.ts
  src/shared/context/FeatureFlag/flags.utils.ts
  src/shared/context/FeatureFlag/index.ts
  src/shared/context/FeatureFlag/withFeatureFlag.test.tsx
  src/shared/context/FeatureFlag/withFeatureFlag.tsx
  src/shared/context/FeatureFlag/withServerFeatureFlag.test.tsx
  src/shared/context/FeatureFlag/withServerFeatureFlag.tsx
  src/shared/context/flags.ts
Labels: collective-rewards

#1033 TOK-758/thegraph-fallback
  package-lock.json
  package.json
  src/app/collective-rewards/metrics/components/ABIMetrics/ABIMetrics.tsx
  src/app/providers/ContextProviders.tsx
  src/app/shared/components/Fallback/FallbackWithRetry.tsx
  src/components/ErrorPage/ErrorBoundary.tsx
  src/components/ErrorPage/ErrorThrowerContext.tsx
  src/components/ErrorPage/GlobalErrorBoundary.tsx
  src/components/ErrorPage/index.ts
  src/components/Header/ConnectButton.tsx
Labels: do not merge, collective-rewards

#1034 New Tooltip Integration
  .gitignore
  .storybook/preview.tsx
  src/app/backing/components/builder-card/BuilderHeader/BuilderHeader.tsx
  src/app/layout.tsx
  src/components/ButtonNew/Button.tsx
  src/components/Tooltip/Tooltip.stories.tsx
  src/components/Tooltip/Tooltip.tsx
  src/components/TypographyNew/Header.tsx
  src/components/TypographyNew/Label.tsx
  src/components/TypographyNew/Paragraph.tsx
  src/components/TypographyNew/Span.tsx
  src/components/TypographyNew/Typography.tsx
Labels: dao

#1044 feat: update status labels with new design
  src/app/proposals/components/LatestProposalsTable.tsx
  src/app/proposals/components/table-columns/StatusColumn.tsx
  src/app/proposals/hooks/useProposalListData.ts
  src/components/Status/Status.stories.tsx
  src/components/Status/Status.tsx
  src/components/Status/types.ts
  src/theme/base.css
  src/theme/default.css
Labels: dao

#1021 TOK-726/expose-api
  .env.testnet.local
  next.config.mjs
  package-lock.json
  package.json
  src/app/api/backers/[backer]/metrics/rbi/context/route.ts
  src/app/api/metrics/abi/context/route.ts
  src/app/collective-rewards/rewards/backers/RBI.tsx
  src/app/collective-rewards/rewards/backers/hooks/useGetBackerStakingHistory.ts
  src/app/collective-rewards/rewards/backers/hooks/useGetRBI.ts
  src/config/features.conf.ts
  src/lib/constants.ts
  src/lib/db.ts
Labels: collective-rewards

#1036 Tok 746/tok 765/column dropdown
  package-lock.json
  package.json
  src/app/builders/components/BecomeBuilderBanner/BecomeBuilderBanner.tsx
  src/app/builders/components/DropdownSelector/DropdownSelector.stories.tsx
  src/app/builders/components/DropdownSelector/DropdownSelector.tsx
  src/app/builders/components/DropdownSelector/DropdownSelectorItem.stories.tsx
  src/app/builders/components/DropdownSelector/DropdownSelectorItem.tsx
  src/app/builders/components/Metrics.tsx
  src/app/builders/components/TableColumnDropdown.stories.tsx
  src/app/builders/components/TableColumnDropdown.tsx
  src/components/Icons/CheckboxChecked.tsx
  src/components/Icons/CheckboxUnchecked.tsx
  src/components/Icons/HourglassIcon.tsx
  src/components/Icons/MoreIcon.tsx
  src/components/ProgressBar/ProgressBar.tsx
  src/shared/context/TableContext/types.ts
Labels: collective-rewards

#1042 Tok 746/tok 772/table pager
  src/app/builders/components/BuildersTable/BuildersTablePager.tsx
  src/components/ButtonNew/Button.tsx
  src/components/TableNew/TablePager.stories.tsx
  src/components/TableNew/TablePager.tsx
Labels: collective-rewards

#1039 TOK-761/bottom-action-bar
  src/app/backing/BackingPage.tsx
  src/app/backing/components/BuilderCard/BuilderCardControl.tsx
  src/app/backing/components/BuildersSpotlight/BuildersSpotlight.tsx
  src/app/collective-rewards/allocations/hooks/useAllocateVotes.ts
  src/app/collective-rewards/shared/hooks/useGetEstimatedBackersRewardsPct.ts
  src/components/Button/Button.tsx
  src/components/MainContainer/ContainerDesktop.tsx
  src/components/MainContainer/LayoutProvider.tsx
  src/components/MainContainer/drawers/BottomDrawer.stories.tsx
  src/components/MainContainer/drawers/BottomDrawer.tsx
  src/components/MainContainer/sidebars/SidebarDesktop.tsx
  src/components/Scroll.tsx
  src/components/Typography/Header.tsx
  src/components/Typography/Label.tsx
  src/components/Typography/Paragraph.tsx
  src/components/commonProps.ts
  src/components/containers/ActionsContainer.tsx
  src/components/containers/InfoContainer.tsx
  src/lib/constants.ts
Labels: collective-rewards

#1054 TOK-763: add selector header cell
  src/app/builders/components/Table/SelectorHeaderCell.stories.tsx
  src/app/builders/components/Table/SelectorHeaderCell.tsx
  src/app/builders/components/Table/index.ts
  src/components/Icons/CheckboxChecked.tsx
  src/components/Icons/CheckboxUnchecked.tsx
Labels: collective-rewards

#1053 TOK-762: add table headers
  src/components/TableNew/TableHeaderCell.stories.tsx
  src/components/TableNew/TableHeaderCell.tsx
  src/components/TableNew/TableHeaderNode.stories.tsx
  src/components/TableNew/TableHeaderNode.tsx
  src/components/TableNew/index.ts
Labels: collective-rewards

#1058 TOK-774/collective-rewards-layout-page
  src/app/backing/BackingPage.tsx
  src/app/backing/page.tsx
  src/app/builders/BuildersPage.tsx
  src/app/collective-rewards/CollectiveRewardsPage.tsx
  src/app/collective-rewards/page.tsx
  src/components/containers/PageTitleContainer.stories.tsx
  src/components/containers/PageTitleContainer.tsx
  src/components/containers/index.ts
Labels: collective-rewards

#1048 DAO-1318 Proposal Vote Details Component
  .gitignore
  postcss.config.mjs
  src/app/proposals/components/vote-details/VotingDetails.stories.tsx
  src/app/proposals/components/vote-details/VotingDetails.tsx
  src/app/proposals/components/vote-details/index.ts
  src/shared/utils.ts
  src/theme/base.css
  src/theme/default.css
Labels: dao

#1055 TOK-773/collective-rewards-ctas-container
  src/app/backing/BackingPage.tsx
  src/app/builders/BuildersPage.tsx
  src/app/collective-rewards/components/components/CallToAction/CallToAction.stories.tsx
  src/app/collective-rewards/components/components/CallToAction/CallToAction.tsx
  src/components/containers/ActionMetricsContainer.stories.tsx
  src/components/containers/ActionMetricsContainer.tsx
  src/components/containers/ActionsContainer.stories.tsx
  src/components/containers/ActionsContainer.tsx
  src/components/containers/InfoContainer.stories.tsx
  src/components/containers/InfoContainer.tsx
  src/components/containers/MetricsContainer.stories.tsx
  src/components/containers/MetricsContainer.tsx
  src/theme/design_v3.css
Labels: collective-rewards

#1061 Tok 771/table filter
  src/app/builders/BuilderFilterDropdown.stories.tsx
  src/app/builders/BuilderFilterDropdown.tsx
  src/app/builders/components/MultipleSelectDropdown/MultipleSelectDropdown.stories.tsx
  src/app/builders/components/MultipleSelectDropdown/MultipleSelectDropdown.tsx
  src/app/builders/components/MultipleSelectDropdown/MultipleSelectDropdownItem.stories.tsx
  src/app/builders/components/MultipleSelectDropdown/MultipleSelectDropdownItem.tsx
  src/app/builders/components/MultipleSelectDropdown/index.ts
  src/app/builders/components/TableColumnDropdown.tsx
  src/components/SingleSelectDropdown/SingleSelectDropdown.stories.tsx
  src/components/SingleSelectDropdown/SingleSelectDropdown.tsx
Labels: collective-rewards

#1068 Tok 743/connected backing page
  src/app/backing/BackingPage.tsx
  src/app/backing/components/BackingInfoTitle/BackingInfoTitle.stories.tsx
  src/app/backing/components/BackingInfoTitle/BackingInfoTitle.tsx
  src/app/backing/components/BackingInfoTitle/BackingInfoTitleControl.tsx
  src/app/backing/components/BackingInfoTitle/index.ts
  src/app/backing/components/DottedUnderlineLabel/DottedUnderlineLabel.stories.tsx
  src/app/backing/components/DottedUnderlineLabel/DottedUnderlineLabel.tsx
  src/app/backing/components/Metrics/EstimatedRewardsMetric.tsx
  src/app/backing/components/Popovers/EstimatedRewardsPopover.tsx
  src/app/backing/components/RewardsInfo/RewardsInfo.tsx
  src/app/builders/BuilderFilterDropdown.tsx
  src/components/containers/MetricsContainer.tsx
Labels: collective-rewards

#1063 chore: init commit
  src/components/Icons/AdjustBackingIcon.tsx
  src/components/Icons/BackBuilderIcon.tsx
  src/components/Icons/RemoveBackingIcon.tsx
  src/components/TableNew/ActionCell.stories.tsx
  src/components/TableNew/ActionCell.tsx
Labels: collective-rewards

#1077 Tok 785/rewards cell
  src/app/backing/components/Metrics/EstimatedRewardsMetric.tsx
  src/app/backing/components/Popovers/RifRbtcPopover.tsx
  src/app/backing/components/RewardsInfo/RewardsInfo.tsx
  src/app/builders/components/Table/RewardsCell.stories.tsx
  src/app/builders/components/Table/RewardsCell.tsx
  src/components/DottedUnderlineLabel/DottedUnderlineLabel.stories.tsx
  src/components/DottedUnderlineLabel/DottedUnderlineLabel.tsx
  src/components/RifRbtcTooltip/RifRbtcTooltip.stories.tsx
  src/components/RifRbtcTooltip/RifRbtcTooltip.tsx
Labels: collective-rewards

#1089 Tok 787/backer rewards pct cell
  src/app/backing/components/BackerPercentage/BackerRewardsPercentage.tsx
  src/app/builders/components/Table/BackersPercentage.stories.tsx
  src/app/builders/components/Table/BackersPercentageCell.tsx
  src/components/DeltaIndicator/DeltaIndicator.stories.tsx
  src/components/DeltaIndicator/DeltaIndicator.tsx
  src/theme/design_v3.css
Labels: collective-rewards

#1092 build: enable v3 design in qa
  .env.cr.qa
Labels: collective-rewards

#1083 Proposal list redesign
  src/app/proposals/components/LatestProposalsTable.stories.tsx
  src/app/proposals/components/LatestProposalsTable.tsx
  src/app/proposals/components/SearchButton.tsx
  src/app/proposals/components/filter/FilterButton.tsx
  src/app/proposals/components/filter/FilterRadioItem.stories.tsx
  src/app/proposals/components/filter/FilterRadioItem.tsx
  src/app/proposals/components/filter/FilterSideBar.stories.tsx
  src/app/proposals/components/filter/FilterSideBar.tsx
  src/app/proposals/components/filter/filterOptions.ts
  src/app/proposals/components/mockProposalData.ts
  src/app/proposals/components/pagination/Chevron.tsx
  src/app/proposals/components/pagination/Pagination.tsx
  src/app/proposals/components/pagination/PaginationArrowButton.tsx
  src/app/proposals/components/pagination/PaginationPageNumbers.tsx
  src/app/proposals/components/pagination/PaginationPageSizeSelector.tsx
  src/app/proposals/components/table-columns/CategoryColumn.tsx
  src/app/proposals/components/table-columns/ProposalNameColumn.tsx
  src/app/proposals/components/table-columns/SentimentColumn.tsx
  src/app/proposals/components/table-columns/StatusColumn.tsx
  src/app/proposals/components/table-columns/TimeColumn.tsx
  src/app/proposals/components/table-columns/VotesColumn.tsx
  src/app/proposals/components/table-columns/icons/GrantsIcon.tsx
  src/app/proposals/components/table-columns/icons/ToolsIcon.tsx
  src/app/proposals/components/table-columns/icons/TreasuryIcon.tsx
  src/app/proposals/hooks/useGetProposalsWithGraph.ts
  src/app/proposals/hooks/useProposalListData.ts
  src/app/proposals/shared/types.ts
  src/components/Category/Category.tsx
  src/components/Category/types.ts
  src/components/DebounceSearch/DebounceSearch.tsx
  src/components/Icons/CloseIconKoto.tsx
  src/components/Icons/SearchIconKoto.tsx
  src/components/Icons/index.ts
  src/components/PizzaChart/PizzaChart.tsx
  src/components/Status/Status.tsx
  src/components/Table/GridTable.stories.tsx
  src/components/Table/GridTable.tsx
  src/components/Table/Table.stories.tsx
  src/components/Table/components/SortIndicator.tsx
  src/components/Table/components/icons/ArrowIcon.tsx
  src/components/Table/components/icons/DoubleArrowIcon.tsx
  src/components/Table/grid-table.d.ts
  src/components/Table/index.ts
  src/shared/types.ts
Labels: dao

#1091 Tok 784/builder name cell
  src/app/builders/components/Table/BuilderNameCell/BuilderNameCell.stories.tsx
  src/app/builders/components/Table/BuilderNameCell/BuilderNameCell.tsx
  src/components/Icons/ParachuteIcon.tsx
  src/components/Icons/WarningIcon.tsx
Labels: collective-rewards

#1096 Release/merge changes to main
  .env.cr.qa
  .env.dao.qa
  .env.dev
  .env.mainnet
  .env.release-candidate-mainnet
  .env.release-candidate-testnet
  .github/workflows/release-candidate-mainnet.deploy.yaml
  src/app/api/metrics/abi/context/route.ts
Labels: collective-rewards
