Repository RootstockCollective/dao-frontend, pull requests merged in 2025-05, with the labels that each got.

#936 TOK-551: useIsBacker refactor
  .github/scripts/nft_boost/actions.utils.ts
  src/app/collective-rewards/leaderboard/BuildersLeaderBoardContent.tsx
  src/app/collective-rewards/metrics/Metrics.tsx
  src/app/collective-rewards/rewards/MyRewards.tsx
  src/app/collective-rewards/rewards/hooks/index.ts
  src/app/collective-rewards/rewards/hooks/useGetBackerRewardPerTokenPaid.ts
  src/app/collective-rewards/rewards/hooks/useIsBacker.ts
  src/app/collective-rewards/rewards/hooks/useIsBuilderOrBacker.ts
  src/lib/constants.ts
Labels: collective-rewards

#952 TOK-715: trim lastestFile content
  src/app/providers/NFT/BoosterContext.test.tsx
  src/app/providers/NFT/BoosterContext.tsx
  src/app/providers/NFT/boost.utils.ts
Labels: bug, collective-rewards

#971 DAO-1238 Set enableWalletConnect to false in ContextProviders
  src/app/providers/ContextProviders.tsx
Labels: dao

#978 fix(cr): use better modal handles (#945)
  src/app/collective-rewards/metrics/CycleMetrics.tsx
  src/app/collective-rewards/metrics/TotalActiveBuildersMetrics.tsx
  src/app/collective-rewards/metrics/components/ABIMetrics/ABIMetrics.tsx
  src/app/collective-rewards/user/components/Button/BecomeABuilderButton.tsx
  src/components/Modal/BecomeABuilderModal.tsx
  src/components/Modal/Modal.tsx
Labels: collective-rewards

#980 fix(useGetBackerRewards): change gauges list map
  src/app/collective-rewards/allocations/context/AllocationsContext.tsx
  src/app/collective-rewards/allocations/hooks/useBuildersWithBackerRewardPercentage.ts
  src/app/collective-rewards/rewards/backers/BackerRewardsTable.tsx
  src/app/collective-rewards/rewards/backers/context/BackerRewardsContext.tsx
  src/app/collective-rewards/rewards/backers/hooks/useGetBackerRewards.ts
Labels: collective-rewards

#953 TOK-717: change target SC addr for dewhitelist
  src/app/proposals/hooks/useRemoveBuilderProposal.ts
Labels: bug, do not merge, collective-rewards, ready-for-qa

#997 TOK-739: create backing page structure
  .env.testnet.local
  src/app/backing/BackingPage.tsx
  src/app/backing/components/Container/ActionMetricsContainer.stories.tsx
  src/app/backing/components/Container/ActionMetricsContainer.tsx
  src/app/backing/components/Container/ActionsContainer.stories.tsx
  src/app/backing/components/Container/ActionsContainer.tsx
  src/app/backing/components/Container/InfoContainer.stories.tsx
  src/app/backing/components/Container/InfoContainer.tsx
  src/app/backing/components/Container/MetricsContainer.stories.tsx
  src/app/backing/components/Container/MetricsContainer.tsx
  src/app/backing/components/Container/PageTitleContainer.stories.tsx
  src/app/backing/components/Container/PageTitleContainer.tsx
  src/app/backing/components/Container/index.ts
  src/app/backing/components/H/H1.stories.tsx
  src/app/backing/components/H/H1.tsx
  src/app/backing/components/H/index.ts
  src/app/backing/components/commonProps.ts
  src/app/backing/components/index.ts
  src/app/backing/page.tsx
  src/shared/context/FeatureFlagContext.tsx
  src/shared/context/flags.ts
  src/theme/default.css
  src/theme/design_v3.css
Labels: collective-rewards

#1009 TOK-693: remove datatest-id propagation
  .env.testnet.local
  src/app/backing/BackingPage.tsx
  src/app/backing/components/Container/ActionMetricsContainer.stories.tsx
  src/app/backing/components/Container/ActionMetricsContainer.tsx
  src/app/backing/components/Container/ActionsContainer.stories.tsx
  src/app/backing/components/Container/ActionsContainer.tsx
  src/app/backing/components/Container/InfoContainer.stories.tsx
  src/app/backing/components/Container/InfoContainer.tsx
  src/app/backing/components/Container/MetricsContainer.stories.tsx
  src/app/backing/components/Container/MetricsContainer.tsx
  src/app/backing/components/Container/PageTitleContainer.stories.tsx
  src/app/backing/components/Container/PageTitleContainer.tsx
  src/app/backing/components/commonProps.ts
  src/app/backing/page.tsx
  src/shared/context/FeatureFlag/FeatureFlagContext.tsx
  src/shared/context/FeatureFlag/flags.ts
  src/shared/context/FeatureFlag/index.ts
Labels: collective-rewards

#998 TOK-740: create metric component
  src/app/backing/components/H/H1.stories.tsx
  src/app/backing/components/H/H1.tsx
  src/app/backing/components/H/index.ts
  src/app/backing/components/IconButton/InfoIconButton.stories.tsx
  src/app/backing/components/IconButton/InfoIconButton.tsx
  src/app/backing/components/Metric/Metric.stories.tsx
  src/app/backing/components/Metric/Metric.tsx
  src/app/backing/components/Metric/MetricContent.stories.tsx
  src/app/backing/components/Metric/MetricContent.tsx
  src/app/backing/components/Metric/MetricTitle.stories.tsx
  src/app/backing/components/Metric/MetricTitle.tsx
  src/app/backing/components/commonProps.ts
  src/app/backing/components/index.ts
  src/app/collective-rewards/rewards/components/Tooltip.tsx
  src/components/Icons/KotoQuestionMarkIcon.tsx
  src/theme/default.css
Labels: collective-rewards
