Repository RootstockCollective/dao-frontend, pull requests merged in 2025-03, with the labels that each got.

#754 TOK-648: show nft thumb in boost card
  src/app/shared/components/NFTBoosterCard/SelfContainedNFTBoosterCard.tsx
Labels: collective-rewards

#758 fix(boost_gha): avoids confict and removes .txt silliness
  .github/scripts/nft_boost/activateBoost.ts
  .github/workflows/booster-deactivate.yaml
  .github/workflows/booster.yaml
Labels: bug, collective-rewards

#720 TOK-618: boosted est rewards
  .env.testnet.local
  src/app/collective-rewards/rewards/backers/ABIBackers.tsx
  src/app/collective-rewards/rewards/backers/ClaimableRewards.tsx
  src/app/collective-rewards/rewards/backers/Rewards.tsx
  src/app/collective-rewards/rewards/backers/RewardsCard.tsx
  src/app/collective-rewards/rewards/backers/index.ts
  src/app/collective-rewards/rewards/components/MetricContainer.tsx
  src/app/collective-rewards/rewards/components/MetricsCard.tsx
  src/app/collective-rewards/rewards/types.ts
  src/app/providers/NFT/BoosterContext.test.tsx
  src/app/providers/NFT/BoosterContext.tsx
  src/components/BoltSvg/BoltSvg.tsx
  src/components/Label/GlowingLabel.tsx
Labels: collective-rewards

#765 TOK-655: lowercase addresses in gen data
  .github/scripts/nft_boost/activateBoost.ts
  .github/scripts/nft_boost/process.utils.ts
  .github/workflows/booster.yaml
Labels: bug, collective-rewards

#742 Refactor icons into separate components for better modularity
  src/app/collective-rewards/shared/components/Table/TableCells.tsx
  src/app/collective-rewards/shared/components/Table/TableHeaders.tsx
  src/components/Icons/ArrowDownIcon.tsx
  src/components/Icons/ArrowDownSFillIcon.tsx
  src/components/Icons/ArrowUpIcon.tsx
  src/components/Icons/ArrowUpSFillIcon.tsx
  src/components/Icons/CircleIcon.tsx
  src/components/Icons/Icons.stories.tsx
  src/components/Icons/constants.ts
  src/components/Icons/index.ts
  src/components/Icons/types.ts
Labels: urgent

#784 TOK-647: glow active campaign user page
  src/app/user/Communities/CommunitiesSection.tsx
  src/app/user/Communities/CommunityCard.tsx
  src/app/user/types.ts
Labels: collective-rewards

#762 Convert react-icons to components - 2
  src/app/communities/CommunityItem.tsx
  src/app/communities/nft/[address]/HolderColumn.tsx
  src/app/communities/nft/[address]/NftHoldersSection.tsx
  src/app/communities/nft/[address]/page.tsx
  src/app/treasury/HoldersSection.tsx
  src/components/Button/Button.stories.tsx
  src/components/Footer/Footer.tsx
  src/components/Icons/ArrowUpRightIcon.tsx
  src/components/Icons/DiscordIcon.tsx
  src/components/Icons/ExternalLinkIcon.tsx
  src/components/Icons/Icons.stories.tsx
  src/components/Icons/LinkIcon.tsx
  src/components/Icons/TwitterXIcon.tsx
  src/components/Icons/index.ts
Labels: urgent

#774 TOK-657: add activation date
  .github/scripts/nft_boost/actions.utils.ts
  .github/scripts/nft_boost/activateBoost.ts
  .github/workflows/booster.yaml
  src/app/communities/communityUtils.tsx
  src/app/communities/nft/[address]/page.tsx
  src/app/providers/NFT/BoosterContext.tsx
Labels: collective-rewards

#788 fix/show owned nft
  .env.mainnet
  .github/scripts/nft_boost/activateBoost.ts
  src/app/collective-rewards/rewards/backers/Rewards.tsx
  src/app/collective-rewards/rewards/components/MetricContainer.tsx
  src/app/collective-rewards/rewards/components/MetricsCard.tsx
  src/app/collective-rewards/rewards/components/Section/RewardsSectionHeader.tsx
  src/app/communities/CommunityItem.test.tsx
  src/app/communities/CommunityItem.tsx
  src/app/communities/components/BoostedBox.tsx
  src/app/communities/components/BoostedLabel.tsx
  src/app/communities/hooks/useIsBoosted.ts
  src/app/communities/nft/[address]/page.tsx
  src/app/providers/NFT/BoosterContext.test.tsx
  src/app/providers/NFT/BoosterContext.tsx
  src/app/shared/components/NFTBoosterCard/SelfContainedNFTBoosterCard.test.tsx
  src/app/shared/components/NFTBoosterCard/SelfContainedNFTBoosterCard.tsx
  src/app/user/Communities/CommunitiesSection.tsx
Labels: collective-rewards

#799 TOK-659/estimated-rewards-tooltip
  src/app/collective-rewards/rewards/backers/Rewards.tsx
Labels: collective-rewards

#797 DAO-1130 Added /lib folder to be detected as a source by Tailwind CSS…
  src/app/user/Delegation/DelegationSection.tsx
  src/app/user/HeroSection/HeroSection.tsx
  src/components/Header/AccountAddress.tsx
  src/components/MainContainer/MainContainer.tsx
  src/shared/walletConnection/components/ConnectButtonComponent.tsx
  src/shared/walletConnection/components/DisclaimerFlowModal.tsx
  src/shared/walletConnection/components/DisconnectButton.tsx
  src/shared/walletConnection/components/index.ts
  src/shared/walletConnection/components/topPageHeader/TopPageHeader.tsx
  src/shared/walletConnection/components/topPageHeader/TopPageHeaderLeftSlotStrategy.tsx
  src/shared/walletConnection/components/topPageHeader/index.ts
  src/shared/walletConnection/components/topPageHeader/pages/UserTopLeftComponent.tsx
  src/shared/walletConnection/components/topPageHeader/pages/index.ts
  src/shared/walletConnection/connection/ConnectWorkflow.tsx
  src/shared/walletConnection/connection/DisconnectWorkflow.tsx
  src/shared/walletConnection/connection/UserConnectionManager.tsx
  src/shared/walletConnection/connection/index.ts
  src/shared/walletConnection/constants.tsx
  src/shared/walletConnection/index.ts
  src/shared/walletConnection/types.ts
  src/shared/walletConnection/utils.ts
  tailwind.config.ts
Labels: dao

#786 DAO-1117: Implement New Balances Section when user is not connected
  src/app/collective-rewards/shared/components/CRWhitepaperLink.tsx
  src/app/user/Balances/BalancesSection.tsx
  src/app/user/Balances/StakeRIFCell.tsx
  src/app/user/Balances/UnStakeRIFCell.tsx
  src/components/Popover/Popover.tsx
  src/components/SectionHeader/SectionHeader.tsx
  src/components/SectionHeader/index.tsx
  src/components/section-header/index.tsx
Labels: dao

#770 DAO-1125: proposal detail page
  src/app/proposals/[id]/page.tsx
  src/app/proposals/components/ProposalQuorum.tsx
  src/app/proposals/layout.tsx
  src/app/proposals/server/getQuorumByBlockNumber.tsx
  src/components/Breadcrumb/Breadcrumb.tsx
  src/components/Icons/HomeIcon.tsx
  src/shared/walletConnection/components/topPageHeader/pages/ProposalDetailTopLeftComponent.tsx
  src/shared/walletConnection/components/topPageHeader/pages/index.ts
  src/shared/walletConnection/constants.tsx
Labels: dao

#804 Dao 1146 Added proposal list sign posting and create proposal button in the new top page header
  src/app/proposals/components/HeaderSection.tsx
  src/app/proposals/page.tsx
  src/shared/walletConnection/components/topPageHeader/pages/ProposalsTopLeftComponent.tsx
  src/shared/walletConnection/components/topPageHeader/pages/index.ts
  src/shared/walletConnection/constants.tsx
Labels: dao

#812 Removed become a builder button from the CR screen
  src/app/collective-rewards/metrics/Metrics.tsx
Labels: dao

#775 Env/rename cr qa
  .env.cr.qa
  .github/workflows/cr.qa.deploy.yaml
  README.md
Labels: collective-rewards

#815 TOK-651: my-rewards-wallet-not-connected
  public/images/my-rewards-empty-state.png
  src/app/collective-rewards/metrics/Metrics.tsx
  src/app/collective-rewards/rewards/MyRewards.tsx
  src/app/collective-rewards/rewards/backers/BackerRewardsTable.tsx
  src/app/collective-rewards/user/components/Button/BecomeABuilderButton.tsx
  src/app/user/Balances/BalancesSection.tsx
  src/app/user/page.tsx
  src/components/Tabs/Tabs.tsx
Labels: collective-rewards

#818 feat: animate header become builder button
  src/shared/walletConnection/components/topPageHeader/TopPageHeader.tsx
Labels: collective-rewards

#783 DAO-1119 Implement new Communities section on the homepage
  public/images/loading-card.png
  public/images/nfts/empty-nft-cover.png
  src/app/user/Communities/CommunitiesSection.tsx
  src/app/user/Communities/CommunityCard.tsx
  src/app/user/Communities/JoinACommunity.tsx
  src/app/user/types.ts
  src/components/SectionHeader/SectionHeader.tsx
  src/components/SectionHeader/index.tsx
  src/components/Typography/Header.tsx
  src/components/loading-components/CardPlaceholder.tsx
  src/components/loading-components/index.ts
Labels: dao

#806 chore(): update with hotfix v1.6.1
  .env.mainnet
  .github/scripts/nft_boost/activateBoost.ts
  package-lock.json
  package.json
  src/app/collective-rewards/rewards/backers/Rewards.tsx
  src/app/collective-rewards/rewards/components/MetricContainer.tsx
  src/app/collective-rewards/rewards/components/MetricsCard.tsx
  src/app/collective-rewards/rewards/components/Section/RewardsSectionHeader.tsx
  src/app/collective-rewards/user/components/Button/BecomeABuilderButton.tsx
  src/app/communities/CommunityItem.test.tsx
  src/app/communities/CommunityItem.tsx
  src/app/communities/components/BoostedBox.tsx
  src/app/communities/components/BoostedLabel.tsx
  src/app/communities/nft/[address]/page.tsx
  src/app/providers/NFT/BoosterContext.test.tsx
  src/app/providers/NFT/BoosterContext.tsx
  src/app/shared/components/NFTBoosterCard/SelfContainedNFTBoosterCard.test.tsx
  src/app/shared/components/NFTBoosterCard/SelfContainedNFTBoosterCard.tsx
  src/app/user/Communities/CommunitiesSection.tsx
Labels: collective-rewards

#821 TOK-646: update my collective tabs design
  src/components/Tabs/Tabs.tsx
Labels: collective-rewards

#801 DAO-1124: proposal list page
  src/app/proposals/components/LatestProposalsTable.tsx
  src/app/proposals/components/table-columns/CategoryColumn.tsx
  src/app/proposals/components/table-columns/ProposalNameColumn.tsx
  src/app/proposals/hooks/useProposalListData.ts
  src/app/proposals/hooks/useVotingPower.ts
  src/app/proposals/page.tsx
  src/components/Category/Category.tsx
  src/components/Category/types.ts
Labels: dao

#823 Refactor icon usage to custom components
  package-lock.json
  package.json
  src/app/collective-rewards/settings/builder/BuilderRewardsSettingsForm.tsx
  src/app/proposals/[id]/page.tsx
  src/app/proposals/create/CreateProposalHeaderSection.tsx
  src/components/Collapsible/Collapsible.tsx
  src/components/Footer/Footer.tsx
  src/components/Icons/ArrowUpRightLightIcon.tsx
  src/components/Icons/ChevronDownIcon.tsx
  src/components/Icons/ChevronUpIcon.tsx
  src/components/Icons/GitHubIcon.tsx
  src/components/Icons/Icons.stories.tsx
  src/components/Icons/MinusIcon.tsx
  src/components/Icons/RocketIcon.tsx
  src/components/Icons/TelegramIcon.tsx
  src/components/Icons/index.ts
  src/components/Link/ExternalLink.tsx
Labels: urgent, dao

#824 DAO-1130-5 Fixed 5 steps to get started not refreshing when browsing.
  src/app/proposals/actions/proposalsAction.ts
  src/app/proposals/hooks/useVotingPower.ts
  src/components/MainContainer/MainContainer.tsx
  src/components/Scroll.tsx
  src/lib/viemPublicClient.ts
  src/shared/walletConnection/components/topPageHeader/pages/ProposalsTopLeftComponent.tsx
  src/shared/walletConnection/components/topPageHeader/pages/UserTopLeftComponent.tsx
Labels: dao

#828 fix: loading state in my rewards
  src/app/collective-rewards/rewards/MyRewards.tsx
Labels: collective-rewards

#826 fix: wait until the data is ready before redirecting
  src/app/collective-rewards/settings/Settings.tsx
Labels: collective-rewards

#822 TOK-666: move the nft card
  src/app/collective-rewards/metrics/Metrics.tsx
  src/app/collective-rewards/shared/components/JustifyBetweenLayout.tsx
  src/app/collective-rewards/shared/components/index.ts
  src/app/communities/nft/[address]/_sections/UserMemberSection.tsx
  src/app/communities/nft/[address]/page.tsx
  src/app/providers/NFT/BoosterContext.tsx
  src/app/shared/components/NFTBoosterCard/SelfContainedNFTBoosterCard.test.tsx
  src/app/shared/components/NFTBoosterCard/SelfContainedNFTBoosterCard.tsx
  src/shared/constants/index.ts
  src/shared/constants/routes.ts
  src/shared/constants/text/index.ts
  src/shared/contants/index.ts
  src/shared/walletConnection/components/topPageHeader/TopPageHeader.tsx
  src/shared/walletConnection/components/topPageHeader/pages/UserTopLeftComponent.tsx
Labels: collective-rewards

#834 HOTFIX - Fixed search icon alignment in Activated Builders -> Input.tsx
  src/components/Input/Input.tsx
Labels: dao

#790 TOK-643: RBI
  .env.cr.qa
  .env.mainnet
  .env.release-candidate
  .env.testnet.local
  src/app/collective-rewards/metrics/components/ABIMetrics/ABIMetrics.tsx
  src/app/collective-rewards/metrics/context/CycleContext.tsx
  src/app/collective-rewards/rewards/backers/RBI.tsx
  src/app/collective-rewards/rewards/backers/Rewards.tsx
  src/app/collective-rewards/rewards/backers/actions.ts
  src/app/collective-rewards/rewards/backers/hooks/index.ts
  src/app/collective-rewards/rewards/backers/hooks/useGetBackerStakingHistory.ts
  src/app/collective-rewards/rewards/backers/hooks/useGetRBI.ts
  src/app/collective-rewards/rewards/backers/index.ts
  src/app/collective-rewards/rewards/hooks/useGetLastCycleDistribution.test.tsx
  src/app/collective-rewards/rewards/types.ts
  src/app/collective-rewards/shared/hooks/useGaugesGetFunction.ts
Labels: do not merge, collective-rewards

#827 fix: always show builder button when user is connected
  src/shared/walletConnection/components/topPageHeader/TopPageHeader.tsx
Labels: collective-rewards

#836 DAO-1124: remove proposal category, remove arrow icon, and include proposal states
  src/app/proposals/[id]/page.tsx
  src/app/proposals/components/LatestProposalsTable.tsx
  src/app/proposals/components/table-columns/ProposalNameColumn.tsx
Labels: dao

#837 HOTFIX - Will now use query instead of useEffect for added benefits o…
  src/app/proposals/hooks/useVotingPower.ts
Labels: dao

#838 DAO-1155 fix add to wallet button
  src/app/communities/nft/[address]/CommunityNFTContext.tsx
  src/app/communities/nft/[address]/_sections/MembershipNFTSection.tsx
  src/app/communities/nft/[address]/_sections/UserMemberSection.tsx
Labels: dao

#840 Minor fix to be sure that the text renders correctly without a huge s…
  src/app/communities/nft/[address]/_sections/UserMemberSection.tsx
Labels: dao

#841 Fix issues on treasury page and enhance metrics display
  src/app/treasury/MetricsSection.tsx
  src/app/treasury/TabsSection.tsx
  src/app/treasury/hooks/useTabCards.ts
  src/app/user/Delegation/DelegationSection.tsx
  src/components/MetricsCard/MetricsCard.tsx
  src/components/Modal/VoteProposalModal.tsx
Labels: urgent, dao

#845 DAO-1124: fix delegated voting power
  src/app/proposals/hooks/useVotingPower.ts
  src/app/proposals/page.tsx
Labels: dao

#850 DAO-1158 Fixed hydration error when attempting to show the address.
  src/shared/walletConnection/connection/UserConnectionManager.tsx
Labels: dao

#856 TOK-653/remove-migration-support
  .env.cr.qa
  .env.dev
  .env.mainnet
  .env.release-candidate
  .env.testnet
  .env.testnet.local
  src/app/collective-rewards/allocations/hooks/useBuildersWithBackerRewardPercentage.ts
  src/app/collective-rewards/rewards/builders/hooks/useGetRewardPercentageToApply.ts
  src/app/collective-rewards/rewards/hooks/useGetBackerRewardPercentage.ts
  src/app/collective-rewards/rewards/hooks/useGetBackersRewardPercentage.ts
  src/app/collective-rewards/settings/builder/hooks/useBuilderConfig.ts
  src/app/collective-rewards/user/hooks/useGetBuilderToGauge.ts
  src/app/collective-rewards/user/hooks/useGetBuilders.ts
  src/app/collective-rewards/user/hooks/useGetGaugesArray.ts
  src/app/collective-rewards/user/hooks/useGetGaugesLength.ts
  src/app/proposals/hooks/useCreateBuilderWhitelistProposal.ts
  src/app/providers/ContextProviders.tsx
  src/lib/constants.ts
  src/shared/context/MigrationContext.test.tsx
  src/shared/context/MigrationContext.tsx
Labels: collective-rewards
