Repository RootstockCollective/dao-frontend, pull requests merged in 2025-04, with the labels that each got.

#891 DAO-1166 Double the width of the proposal name column
  src/app/proposals/components/LatestProposalsTable.tsx
  src/components/Table/StatefulTable.tsx
Labels: dao

#897 DAO-1184 Updated next.js to latest version. At the same time axios up…
  package-lock.json
  package.json
Labels: collective-rewards, dao

#899 IPFS - Centralize logic
  .env.cr.qa
  .env.dev
  .env.mainnet
  .env.release-candidate
  .env.staging.mainnet
  .env.testnet
  .env.testnet.local
  src/app/communities/CommunityItem.tsx
  src/app/communities/nft/[address]/CommunityNFTContext.tsx
  src/app/communities/nft/[address]/_components/HolderColumn.tsx
  src/app/communities/nft/[address]/_sections/MembershipNFTSection.tsx
  src/app/communities/nft/[address]/_sections/NftHoldersSection.tsx
  src/app/communities/nft/server/fetchNftHolders.ts
  src/app/user/Balances/actions.ts
  src/app/user/Communities/CommunitiesSection.tsx
  src/app/user/Communities/CommunityCard.tsx
  src/app/user/types.ts
  src/components/loading-components/CardPlaceholder.tsx
  src/lib/constants.ts
  src/lib/ipfs.test.ts
  src/lib/ipfs.ts
  src/shared/hooks/useCommunity.ts
Labels: dao

#896 feat: impl discussion link on communities page
  src/app/communities/communityUtils.tsx
  src/app/communities/nft/[address]/page.tsx
Labels: dao

#908 Add crossOrigin attribute to Image components for improved CORS handling
  src/app/communities/nft/[address]/_components/HolderColumn.tsx
  src/app/communities/nft/[address]/_sections/MembershipNFTSection.tsx
  src/app/communities/nft/[address]/_sections/NftHoldersSection.tsx
  src/app/user/Communities/CommunityCard.tsx
Labels: bug, dao

#868 DAO-961-FINAL Edited files to remove Number dependency and wrong floa…
  src/app/collective-rewards/allocations/components/BuilderAllocation.tsx
  src/app/proposals/hooks/useGetProposalVotes.ts
  src/app/user/Stake/StakePreviewBalance.tsx
  src/lib/utils.ts
Labels: dao

#915 Replaced buggy tab behavior with animated UnderlineTabs component for smoother UX
  src/app/user/page.tsx
Labels: dao

#945 fix(cr): use better modal handles
  package-lock.json
  package.json
  src/app/collective-rewards/metrics/AllTimeRewardsMetrics.tsx
  src/app/collective-rewards/metrics/CycleMetrics.tsx
  src/app/collective-rewards/metrics/TotalActiveBuildersMetrics.tsx
  src/app/collective-rewards/metrics/TotalAllocationsMetrics.tsx
  src/app/collective-rewards/metrics/components/ABIMetrics/ABIMetrics.tsx
  src/app/collective-rewards/rewards/backers/ClaimableRewards.tsx
  src/app/collective-rewards/rewards/backers/RewardsCard.tsx
  src/app/collective-rewards/rewards/builders/AllTimeRewards.tsx
  src/app/collective-rewards/rewards/builders/ClaimableRewards.tsx
  src/app/collective-rewards/rewards/builders/EstimatedRewards.tsx
  src/app/collective-rewards/rewards/builders/LastCycleRewards.tsx
  src/app/collective-rewards/user/components/Button/BecomeABuilderButton.tsx
  src/components/LoadingSpinner/LoadingSpinner.stories.tsx
  src/components/LoadingSpinner/LoadingSpinner.tsx
  src/components/LoadingSpinner/index.ts
  src/components/LoadingSpinner/withLoadingSpinner.tsx
  src/components/Modal/BecomeABuilderModal.tsx
  src/components/Modal/Modal.tsx
Labels: bug, collective-rewards

#949 fix: don't show holders section at all for community with 0 holders
  src/app/communities/nft/[address]/_sections/NftHoldersSection.tsx
Labels: do not merge
